language: objective-c
osx_image: xcode8
git:
  submodules: false
before_install:
  - rvm get head
  - gem install cocoapods --no-document --quiet
  - gem install xcpretty --no-document --quiet
  - pod repo update
install: script/install
script: script/test