language: objective-c
osx_image: xcode7.3
git:
  submodules: false
before_install:
  - rvm get head
  - gem install cocoapods --no-document --quiet
  - gem install xcpretty --no-document --quiet
install: script/install
script: script/test