language: objective-c
osx_image: xcode8
git:
  submodules: false
before_install:
  - rvm get head
  - gem install cocoapods -v 1.1.0.rc.2 --no-document --quiet
  - gem install xcpretty --no-document --quiet
install: script/install
script: script/test