language: objective-c
osx_image: xcode7
git:
  submodules: false
before_install:
  - brew update; brew update
  - brew install carthage
  - git submodule update --init
install: script/update
script: script/test
