language: objective-c
osx_image: xcode7.3
git:
  submodules: false
before_install:
  - rvm get head
  - brew update
  - brew unlink carthage
  - brew install carthage
install: script/install
script: script/test