#!/usr/bin/env bash

jazzy \
  --author "The Grid" \
  --author_url "https://thegrid.io" \
  --github_url "https://github.com/the-grid/Disc" \
  --module Disc \
  --output Documentation \
  --skip-undocumented \
